### ISSUE TITLE
[Feat] Setup circleci

### ISSUE THREAD

**Issue by ixje** [CityOfZion/neo3-python#1]
Setup Circle CI to
- run `mypy` and the `unittests` for both python 3.7 & 3.8 as there are differences in execution for both
- [X] run `make type`
- [X] run `make lint`
- [X] run `make test`
- [ ] run `make docs`
- [x] run `make coverage`  - do not fail if coverage is lower, just for reporting
- [ ] push to PyPi if there is a release/tag

**Comment by ixje** [comment]
here's what I have until now. 
-edit2-
circleci stinks and only understand `venv` commands if `venv` enabling and command execution happens in 1 step 😤 . Anyway below is a working config, but only for 3.8 and not complete
```
version: 2.1

executors:
  python38-executor:
    docker:
      - image: circleci/python:3.8.2-buster
  python37-executor:
    docker:
      - image: circleci/python:3.7.7-buster

jobs:
  setup-environment:
    executor: python38-executor
    steps:
      - checkout
      - run:
          name: Version information
          command: python --version
      - run:
          name: Setup VENV & install dependencies
          command: |
            python -m venv venv
            source venv/bin/activate
            pip install -e .
      - persist_to_workspace:
          root: ~/
          paths: project/*
  unit-tests:
    executor: python38-executor
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Unit tests
          command: |
            source venv/bin/activate
            make test
  linting:
    executor: python38-executor
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Python code style checking
          command: |
            source venv/bin/activate
            make lint
  type-checking:
    executor: python38-executor
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Type checking
          command: |
            source venv/bin/activate
            make type

workflows:
  main:
    jobs:
      - setup-environment
      - type-checking:
          requires:
            - setup-environment
      - linting:
          requires:
            - setup-environment
      - unit-tests:
          requires:
            - setup-environment
```
